name = "roykung-com"
main = "./.output/worker/entry.mjs"
compatibility_date = "2024-02-20"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".worker-next/assets", binding = "ASSETS" }

[site]
bucket = "./.output/client"
